# Generated by Django 4.0.3 on 2022-05-02 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='price',
        ),
    ]
