# Generated by Django 4.0.3 on 2022-05-25 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_remove_plan_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='trial_days',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
