# Generated by Django 4.0.3 on 2022-07-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_plan_trial_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='trial_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
