services:
  diarios-do-clima-backend-server:
    links:
      - diarios-do-clima-redis:redis

  diarios-do-clima-backend-celery-beat:
    links:
      - diarios-do-clima-redis:redis

  diarios-do-clima-backend-celery-worker:
    links:
      - diarios-do-clima-redis:redis

  diarios-do-clima-nginx:
    build: ./nginx
    restart: always
    ports:
      - "80:80"
    links:
      - diarios-do-clima-backend-server:backend
