services:
  diarios-do-clima-backend-server:
    links:
      - diarios-do-clima-redis:redis
    networks:
      - frontend
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.diarios-backend.rule=Host(`${BACKEND_DOMAIN:-backend.example.com}`)"
      - "traefik.http.routers.diarios-backend.entrypoints=websecure"
      - "traefik.http.routers.diarios-backend.tls=true"
      - "traefik.http.routers.diarios-backend.tls.certresolver=letsencrypt"
      - "traefik.http.services.diarios-backend.loadbalancer.server.port=8000"
      - "traefik.docker.network=frontend"

  diarios-do-clima-backend-celery-beat:
    links:
      - diarios-do-clima-redis:redis
    networks:
      - backend
    labels:
      - "traefik.enable=false"

  diarios-do-clima-backend-celery-worker:
    links:
      - diarios-do-clima-redis:redis
    networks:
      - backend
    labels:
      - "traefik.enable=false"

  diarios-do-clima-redis:
    networks:
      - backend
    labels:
      - "traefik.enable=false"

networks:
  frontend:
    external: true
  backend:
    driver: bridge
