services:
  diarios-do-clima-backend-server:
    links:
      - diarios-do-clima-redis:redis

  diarios-do-clima-backend-celery-beat:
    links:
      - diarios-do-clima-redis:redis

  diarios-do-clima-backend-celery-worker:
    links:
      - diarios-do-clima-redis:redis

  diarios-do-clima-nginx:
    build: ./nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    links:
      - diarios-do-clima-backend-server:backend
    volumes:
      - certbot-verify:/www/certbot:ro
      - certbot-keys:/etc/nginx/ssl:ro

  diarios-do-clima-certbot:
    image: docker.io/certbot/certbot:v2.6.0
    volumes:
      - certbot-verify:/var/www/certbot/:rw
      - certbot-keys:/etc/letsencrypt/:rw

volumes:
  certbot-verify:
  certbot-keys:
