# Generated by Django 4.0.3 on 2022-04-13 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_alter_plan_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='card',
            new_name='html',
        ),
    ]
