# Generated by Django 4.0.3 on 2022-05-02 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_alter_plansubscriptionstatus_pagseguro_notification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plansubscriptionstatus',
            name='pagseguro_notification_code',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
    ]
