# Generated by Django 4.0.3 on 2022-05-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
