# Generated by Django 4.0.3 on 2022-04-28 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagseguro_code', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlanSubscriptionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagseguro_data', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('PAYMENT_METHOD_CHANGE', 'PAYMENT_METHOD_CHANGE')], max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.plansubscription')),
            ],
            options={
                'verbose_name': 'Plan Subscription Status',
                'verbose_name_plural': 'Plan Subscription Statuses',
            },
        ),
    ]
