# Generated by Django 4.0.3 on 2022-04-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plansubscriptionstatus',
            options={'verbose_name': 'Plan Subscription Status', 'verbose_name_plural': 'Plan Subscription Statuses'},
        ),
        migrations.RenameField(
            model_name='plansubscriptionstatus',
            old_name='plan',
            new_name='plan_subscription',
        ),
        migrations.AlterField(
            model_name='plansubscriptionstatus',
            name='data',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('PAYMENT_METHOD_CHANGE', 'PAYMENT_METHOD_CHANGE')], max_length=25),
        ),
    ]
