# Generated by Django 4.0.3 on 2022-05-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plansubscriptionstatus',
            name='pagseguro_notification_code',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='plansubscriptionstatus',
            name='pagseguro_data',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('PAYMENT_METHOD_CHANGE', 'PAYMENT_METHOD_CHANGE'), ('CANCELLED', 'CANCELLED')], max_length=25),
        ),
    ]
