# Generated by Django 4.0.3 on 2022-04-14 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_alter_plansubscriptionstatus_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plansubscriptionstatus',
            old_name='data',
            new_name='pagseguro_data',
        ),
    ]
