# Generated by Django 4.0.3 on 2022-05-25 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_plansubscriptionstatus_pagseguro_notification_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plansubscription',
            name='trial_end_at',
            field=models.DateField(null=True),
        ),
    ]
