# Generated by Django 4.0.3 on 2022-07-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_plansubscription_trial_end_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plansubscriptionstatus',
            name='pagseguro_notification_code',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
