# Generated by Django 4.0.3 on 2022-05-04 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import reports.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('is_public', models.BooleanField(default=False)),
                ('file', models.FileField(upload_to=reports.models.file_upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='ReportUserAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.report')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('report', 'user')},
            },
        ),
    ]
